apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJjMmhoWkc5M2IyNTVlRGt5TFdGbWF6cG5hSEJmZDJaSk5ISlRWRmhpZUZaRWRGbFpTR296UmxCNVVtdExXV2hLV1dsRk5FeHRTSE5aIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
